In [3]:
def wage(work_hours):
    return(work_hours)*5

def bonus(work_hours):
    return wage(work_hours)*5

In [4]:
wage(10),bonus(8)

(50, 200)

In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

In [4]:
import pandas as pd

In [5]:
s = 10

In [6]:
v = np.array([10,-2,4])

In [7]:
v

array([10, -2,  4])

In [8]:
m = np.array([[4,5,6],[7,8,9]])

In [9]:
m

array([[4, 5, 6],
       [7, 8, 9]])

In [10]:
type(m)

numpy.ndarray

In [11]:
m - v

array([[-6,  7,  2],
       [-3, 10,  5]])

In [12]:
type(s)

int